url: "http://localhost:4000"
baseurl: ""
title: "LUUN - Architectural Lighting"

email: 
tagline: "#forluminouspeople"
description: "LUUN is an Athens Greece based company which offers products and services related to architectural lighting."

instagram_username: luun.gr
facebook_username: luun.gr
linkedin_username: luunlight

google:

timezone: Europe/Athens

markdown:  kramdown
permalink: /:categories/:title/
# paginate:  12

plugins:
  - jekyll-sitemap
  # - jekyll-paginate
  - jekyll/tagging
  - jekyll-minifier
  # - jekyll-seo-tag

jekyll-minifier:
  compress_css: false
  compress_javascript: false
  
include:
  - _pages

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

keep_files: 
  - assets
  - sftp-config.json
  - .htaccess

exclude:
  - vendor
  - node_modules
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Gemfile
  - Gemfile.lock
  - jekyll.thor
  - Makefile
  - netlify.toml
  - gulpfile.js
  - package.json
  - package-lock.json
  - README.md
  - README.pdf
  - yarn.lock
  - .htaccessold
  - .htaccessback
  
disable_disk_cache: true
